/-
Copyright (c) 2026 Binary Field Counterexamples Contributors.
Released under Apache 2.0 license.
-/
module
public import BinaryFieldCounterexamples.Counting.GaussianBinomial
public import Mathlib.Algebra.BigOperators.Ring.Finset
public import Mathlib.Algebra.Order.BigOperators.GroupWithZero.Finset
public import Mathlib.Algebra.Order.Field.Rat
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring
/-!
# Exact Gaussian coefficient identities

An integral Pascal recurrence is proved equal to both existing finite product
formulas. The proof establishes the exact ordered-frame product equality before
performing natural division; no integrality or subspace-counting law is assumed.
The resulting symmetry, flag identity, and Newton expansion apply directly to
the unchanged `gaussianBinomial` used in the paper's theorem contracts, at every
integer base greater than one (including the Gold moment base four).
-/

@[expose] public section
namespace BinaryFieldCounterexamples
open scoped BigOperators
/-- Gaussian coefficients generated by their integral Pascal recurrence. -/
def gaussianPascal (q : ℕ) : ℕ → ℕ → ℕ
  | 0, 0 => 1
  | 0, _+1 => 0
  | _+1, 0 => 1
  | n+1, k+1 => gaussianPascal q n k+q^(k+1)*gaussianPascal q n (k+1)
/-- The zeroth Gaussian coefficient is one. -/
theorem gaussianPascal_zero (q n : ℕ) : gaussianPascal q n 0=1 := by
  cases n <;> rfl
/-- Gaussian coefficients vanish above the dimension. -/
theorem gaussianPascal_eq_zero (q n k : ℕ) (h : n<k) : gaussianPascal q n k=0 := by
  induction n generalizing k with
  | zero => cases k <;> simp_all [gaussianPascal]
  | succ n ih =>
    cases k with
    | zero => omega
    | succ k => simp [gaussianPascal, ih k (by omega),ih (k+1) (by omega)]
/-- The diagonal Gaussian coefficient is one. -/
theorem gaussianPascal_self (q n : ℕ) : gaussianPascal q n n=1 := by
  induction n with
  | zero => rfl
  | succ n ih => simp [gaussianPascal,ih,gaussianPascal_eq_zero q n (n+1) (by omega)]
/-- The integral Pascal recurrence for a positive lower index. -/
theorem gaussianPascal_succ (q n k : ℕ) :
    gaussianPascal q (n+1) (k+1)=gaussianPascal q n k+q^(k+1)*gaussianPascal q n (k+1) := by
  rfl
/-- The Newton basis polynomial evaluated at a rational scalar. -/
def gaussianNewtonProduct (q : ℕ) (γ : ℚ) (j : ℕ) : ℚ := ∏ i ∈ Finset.range j, (γ-(q:ℚ)^i)
/-- Multiplication by the scalar advances the Newton basis. -/
theorem gaussianNewtonProduct_step (q : ℕ) (γ : ℚ) (j : ℕ) :
    γ*gaussianNewtonProduct q γ j=gaussianNewtonProduct q γ (j+1)+(q:ℚ)^j*gaussianNewtonProduct q γ j := by
  simp only [gaussianNewtonProduct,Finset.prod_range_succ]
  ring
/-- Gaussian coefficients are the exact Newton expansion coefficients of a power. -/
theorem gaussianPascal_newton (q s : ℕ) (γ : ℚ) :
    ∑ j ∈ Finset.range (s+1), (gaussianPascal q s j:ℚ)*gaussianNewtonProduct q γ j=γ^s := by
  induction s with
  | zero => simp [gaussianPascal,gaussianNewtonProduct]
  | succ s ih =>
    have hzero : gaussianPascal q s (s+1)=0 := gaussianPascal_eq_zero q s (s+1) (by omega)
    have hP0 : gaussianNewtonProduct q γ 0=1 := by simp [gaussianNewtonProduct]
    have hshift : (∑ j ∈ Finset.range (s+1), (q:ℚ)^(j+1)*(gaussianPascal q s (j+1):ℚ)*gaussianNewtonProduct q γ (j+1))+1 =
        ∑ j ∈ Finset.range (s+1), (q:ℚ)^j*(gaussianPascal q s j:ℚ)*gaussianNewtonProduct q γ j := by
      have hh := Finset.sum_range_succ' (fun j => (q:ℚ)^j*(gaussianPascal q s j:ℚ)*gaussianNewtonProduct q γ j) (s+1)
      rw [Finset.sum_range_succ,hzero,Nat.cast_zero,mul_zero,zero_mul,add_zero] at hh
      simpa only [pow_zero,gaussianPascal_zero,Nat.cast_one,hP0,one_mul] using hh.symm
    rw [Finset.sum_range_succ']
    simp only [gaussianPascal_succ,Nat.cast_add,Nat.cast_mul,Nat.cast_pow,add_mul,
      gaussianPascal_zero,Nat.cast_one,hP0,one_mul,Finset.sum_add_distrib]
    rw [add_assoc,hshift,← Finset.sum_add_distrib]
    calc
      _ = ∑ j ∈ Finset.range (s+1), (gaussianPascal q s j:ℚ)*(γ*gaussianNewtonProduct q γ j) := by
        apply Finset.sum_congr rfl
        intro j hj
        rw [gaussianNewtonProduct_step]
        ring
      _ = γ*(∑ j ∈ Finset.range (s+1), (gaussianPascal q s j:ℚ)*gaussianNewtonProduct q γ j) := by
        rw [Finset.mul_sum]
        apply Finset.sum_congr rfl
        intro j hj
        ring
      _ = γ^(s+1) := by rw [ih,pow_succ]; ring
/-- The rational q-factorial used to compare recurrence and product definitions. -/
def gaussianFactorial (q n : ℕ) : ℚ := ∏ i ∈ Finset.range n, ((q:ℚ)^(i+1)-1)
/-- The last factor of a q-factorial. -/
theorem gaussianFactorial_succ (q n : ℕ) :
    gaussianFactorial q (n+1)=gaussianFactorial q n*((q:ℚ)^(n+1)-1) := by
  exact Finset.prod_range_succ _ _
/-- The integral recurrence satisfies the exact q-factorial quotient identity. -/
theorem gaussianPascal_factorial (q n k : ℕ) (hk : k≤n) :
    (gaussianPascal q n k:ℚ)*gaussianFactorial q k*gaussianFactorial q (n-k)=gaussianFactorial q n := by
  induction n generalizing k with
  | zero =>
    have : k=0 := by omega
    subst k
    simp [gaussianPascal,gaussianFactorial]
  | succ n ih =>
    cases k with
    | zero => simp [gaussianPascal_zero,gaussianFactorial]
    | succ k =>
      by_cases he : k=n
      · subst k; simp [gaussianPascal_self,gaussianFactorial]
      have hkn : k<n := by omega
      have hsub : n+1-(k+1)=n-k := by omega
      have hsub' : n-k=(n-(k+1))+1 := by omega
      have h1 := ih k (by omega)
      have h2 := ih (k+1) (by omega)
      have hp : (q:ℚ)^(k+1)*(q:ℚ)^(n-k)=(q:ℚ)^(n+1) := by
        rw [←pow_add]; congr 1; omega
      rw [gaussianPascal_succ,Nat.cast_add,Nat.cast_mul,Nat.cast_pow,hsub]
      calc
        _ = ((gaussianPascal q n k:ℚ)*gaussianFactorial q k*gaussianFactorial q (n-k))*((q:ℚ)^(k+1)-1)+
            (q:ℚ)^(k+1)*((gaussianPascal q n (k+1):ℚ)*gaussianFactorial q (k+1)*gaussianFactorial q (n-(k+1)))*((q:ℚ)^(n-k)-1) := by
          conv_lhs => rw [add_mul,add_mul]
          apply congrArg₂ (· + ·)
          · rw [gaussianFactorial_succ]; ring
          · have hfac := gaussianFactorial_succ q (n-(k+1))
            rw [←hsub'] at hfac
            rw [hfac]; ring
        _ = gaussianFactorial q n*((q:ℚ)^(n+1)-1) := by rw [h1,h2,←hp]; ring
        _ = gaussianFactorial q (n+1) := (gaussianFactorial_succ q n).symm
/-- A q-factorial is nonzero when the base exceeds one. -/
theorem gaussianFactorial_ne_zero (q n : ℕ) (hq : 1<q) : gaussianFactorial q n≠0 := by
  apply Finset.prod_ne_zero_iff.mpr
  intro i hi
  apply sub_ne_zero.mpr
  exact ne_of_gt (one_lt_pow₀ (by exact_mod_cast hq : (1:ℚ)<q) (by omega : i+1≠0))
/-- Descending consecutive factors cancel the complementary factorial. -/
theorem gaussianFactorial_descending (q n k : ℕ) (hk : k≤n) :
    (∏ i ∈ Finset.range k, ((q:ℚ)^(n-i)-1))*gaussianFactorial q (n-k)=gaussianFactorial q n := by
  induction k with
  | zero => simp [gaussianFactorial]
  | succ k ih =>
    have hsub : n-k=(n-(k+1))+1 := by omega
    have hf := gaussianFactorial_succ q (n-(k+1))
    rw [←hsub] at hf
    rw [Finset.prod_range_succ]
    calc
      _ = (∏ i ∈ Finset.range k, ((q:ℚ)^(n-i)-1))*gaussianFactorial q (n-k) := by rw [hf]; ring
      _ = gaussianFactorial q n := ih (by omega)
/-- The rational product definition agrees exactly with the integral recurrence. -/
theorem quadraticGaussian_eq_gaussianPascal (q n k : ℕ) (hq : 1<q) (hk : k≤n) :
    quadraticGaussian q n k=(gaussianPascal q n k:ℚ) := by
  have hden : (∏ i ∈ Finset.range k, ((q:ℚ)^(k-i)-1))=gaussianFactorial q k := by
    simpa [gaussianFactorial] using gaussianFactorial_descending q k k le_rfl
  unfold quadraticGaussian
  rw [Finset.prod_div_distrib,hden]
  apply (div_eq_iff (gaussianFactorial_ne_zero q k hq)).mpr
  apply (mul_right_cancel₀ (gaussianFactorial_ne_zero q (n-k) hq))
  rw [gaussianFactorial_descending q n k hk]
  exact (gaussianPascal_factorial q n k hk).symm
/-- Gaussian symmetry follows from the exact factorial identity. -/
theorem gaussianPascal_symm (q n k : ℕ) (hq : 1<q) (hk : k≤n) :
    gaussianPascal q n k=gaussianPascal q n (n-k) := by
  apply Nat.cast_injective (R := ℚ)
  apply (mul_right_cancel₀ (gaussianFactorial_ne_zero q k hq))
  apply (mul_right_cancel₀ (gaussianFactorial_ne_zero q (n-k) hq))
  rw [gaussianPascal_factorial q n k hk]
  have hh := gaussianPascal_factorial q n (n-k) (by omega)
  rw [Nat.sub_sub_self hk] at hh
  linarith [hh]
/-- Factoring powers out of each ordered-frame factor. -/
theorem gaussianFrameProduct_factor (q n k : ℕ) (hk : k≤n) :
    (∏ i ∈ Finset.range k, ((q:ℚ)^n-(q:ℚ)^i))=
      (∏ i ∈ Finset.range k, (q:ℚ)^i)*(∏ i ∈ Finset.range k, ((q:ℚ)^(n-i)-1)) := by
  rw [←Finset.prod_mul_distrib]
  apply Finset.prod_congr rfl
  intro i hi
  have hi : i≤n := by have := Finset.mem_range.mp hi; omega
  rw [mul_sub,mul_one,←pow_add,Nat.add_sub_of_le hi]
/-- The recurrence coefficients give the exact ordered-frame product quotient. -/
theorem gaussianPascal_frame_product (q n k : ℕ) (hq : 1<q) (hk : k≤n) :
    (gaussianPascal q n k:ℚ)*(∏ i ∈ Finset.range k, ((q:ℚ)^k-(q:ℚ)^i))=
      ∏ i ∈ Finset.range k, ((q:ℚ)^n-(q:ℚ)^i) := by
  have hden : (∏ i ∈ Finset.range k, ((q:ℚ)^(k-i)-1))=gaussianFactorial q k := by
    simpa [gaussianFactorial] using gaussianFactorial_descending q k k le_rfl
  have hnum : (∏ i ∈ Finset.range k, ((q:ℚ)^(n-i)-1))=(gaussianPascal q n k:ℚ)*gaussianFactorial q k := by
    apply mul_right_cancel₀ (gaussianFactorial_ne_zero q (n-k) hq)
    rw [gaussianFactorial_descending q n k hk,gaussianPascal_factorial q n k hk]
  rw [gaussianFrameProduct_factor q n k hk,gaussianFrameProduct_factor q k k le_rfl,hnum,hden]
  ring
/-- Casting the natural ordered-frame product preserves every subtraction. -/
theorem cast_gaussianFrameProduct (q n k : ℕ) (hq : 1<q) (hk : k≤n) :
    ((∏ i ∈ Finset.range k, (q^n-q^i) : ℕ):ℚ)=∏ i ∈ Finset.range k, ((q:ℚ)^n-(q:ℚ)^i) := by
  rw [Nat.cast_prod]
  apply Finset.prod_congr rfl
  intro i hi
  have hi : i≤n := by have := Finset.mem_range.mp hi; omega
  rw [Nat.cast_sub (Nat.pow_le_pow_right (by omega) hi),Nat.cast_pow,Nat.cast_pow]
/-- The original natural product quotient is precisely the integral Pascal coefficient. -/
theorem gaussianBinomial_eq_gaussianPascal (q n k : ℕ) (hq : 1<q) :
    gaussianBinomial q n k=gaussianPascal q n k := by
  by_cases hk : k≤n
  · have he : (∏ i ∈ Finset.range k, (q^n-q^i))=gaussianPascal q n k*(∏ i ∈ Finset.range k, (q^k-q^i)) := by
      apply Nat.cast_injective (R := ℚ)
      rw [Nat.cast_mul,cast_gaussianFrameProduct q n k hq hk,cast_gaussianFrameProduct q k k hq le_rfl]
      exact (gaussianPascal_frame_product q n k hq hk).symm
    have hpos : 0<(∏ i ∈ Finset.range k, (q^k-q^i)) := by
      apply Finset.prod_pos
      intro i hi
      exact Nat.sub_pos_of_lt (Nat.pow_lt_pow_right hq (Finset.mem_range.mp hi))
    simp only [gaussianBinomial,ite_eq_left hk,he,Nat.mul_div_cancel _ hpos]
  · simp [gaussianBinomial,hk,gaussianPascal_eq_zero q n k (by omega)]
/-- A division form of the exact factorial identity. -/
theorem gaussianPascal_eq_factorial_div (q n k : ℕ) (hq : 1<q) (hk : k≤n) :
    (gaussianPascal q n k:ℚ)=gaussianFactorial q n/(gaussianFactorial q k*gaussianFactorial q (n-k)) := by
  apply (eq_div_iff (mul_ne_zero (gaussianFactorial_ne_zero q k hq) (gaussianFactorial_ne_zero q (n-k) hq))).mpr
  simpa only [←mul_assoc] using gaussianPascal_factorial q n k hk
/-- Counting a nested flag in either order gives the same Gaussian product. -/
theorem gaussianPascal_flag (q n k j : ℕ) (hq : 1<q) (hk : k≤n) (hj : j≤k) :
    gaussianPascal q n k*gaussianPascal q k j=gaussianPascal q n j*gaussianPascal q (n-j) (k-j) := by
  apply Nat.cast_injective (R := ℚ)
  rw [Nat.cast_mul,Nat.cast_mul,
    gaussianPascal_eq_factorial_div q n k hq hk,
    gaussianPascal_eq_factorial_div q k j hq hj,
    gaussianPascal_eq_factorial_div q n j hq (by omega),
    gaussianPascal_eq_factorial_div q (n-j) (k-j) hq (by omega)]
  have hs : n-j-(k-j)=n-k := by omega
  rw [hs]
  field_simp [gaussianFactorial_ne_zero q k hq,gaussianFactorial_ne_zero q j hq,
    gaussianFactorial_ne_zero q (n-k) hq,gaussianFactorial_ne_zero q (k-j) hq,
    gaussianFactorial_ne_zero q (n-j) hq]
/-- The paper's natural Gaussian product is the rational Gaussian product in its valid range. -/
theorem cast_gaussianBinomial_eq_quadraticGaussian (q n k : ℕ) (hq : 1<q) (hk : k≤n) :
    (gaussianBinomial q n k:ℚ)=quadraticGaussian q n k := by
  rw [gaussianBinomial_eq_gaussianPascal q n k hq,quadraticGaussian_eq_gaussianPascal q n k hq hk]
/-- Pascal's recurrence for the unchanged natural product definition. -/
theorem gaussianBinomial_succ (q n k : ℕ) (hq : 1<q) :
    gaussianBinomial q (n+1) (k+1)=gaussianBinomial q n k+q^(k+1)*gaussianBinomial q n (k+1) := by
  simp only [gaussianBinomial_eq_gaussianPascal _ _ _ hq,gaussianPascal_succ]
/-- Symmetry for the unchanged natural product definition. -/
theorem gaussianBinomial_symm (q n k : ℕ) (hq : 1<q) (hk : k≤n) :
    gaussianBinomial q n k=gaussianBinomial q n (n-k) := by
  simpa only [gaussianBinomial_eq_gaussianPascal _ _ _ hq] using gaussianPascal_symm q n k hq hk
/-- The Gaussian flag identity in the paper's original natural notation. -/
theorem gaussianBinomial_flag (q n k j : ℕ) (hq : 1<q) (hk : k≤n) (hj : j≤k) :
    gaussianBinomial q n k*gaussianBinomial q k j=gaussianBinomial q n j*gaussianBinomial q (n-j) (k-j) := by
  simpa only [gaussianBinomial_eq_gaussianPascal _ _ _ hq] using gaussianPascal_flag q n k j hq hk hj
/-- The Gaussian Newton identity in the paper's original product notation. -/
theorem gaussianBinomial_newton (q s : ℕ) (hq : 1<q) (γ : ℚ) :
    ∑ j ∈ Finset.range (s+1), (gaussianBinomial q s j:ℚ)*(∏ i ∈ Finset.range j, (γ-(q:ℚ)^i))=γ^s := by
  simpa only [gaussianBinomial_eq_gaussianPascal _ _ _ hq,gaussianNewtonProduct] using gaussianPascal_newton q s γ
end BinaryFieldCounterexamples
